apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria
  labels:
    app: node-app
    env: prod
spec:
  template:
    metadata:
      labels:
        app: lbg4-api
    spec:
      containers:
      - name: maria
        image: gcr.io/lbg-210322/maria:v1
        ports:
        - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: lbg4-api
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: maria
spec:
  selector:
    app: lbg4-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
